# Generated by Django 4.2.29 on 2026-03-22 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycleentry',
            name='oral_contraception',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cycleentry',
            name='protected_sex',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cycleentry',
            name='unprotected_sex',
            field=models.BooleanField(default=False),
        ),
    ]
